In [2]:
import torch
torch.__version__

'2.0.1'

### Creating Tensors

In [7]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# We want to retrieved number from tensor
scalar.item()

7

In [10]:
#Vector is a single dimension tensor
vector = torch.tensor([3, 2])
vector

tensor([3, 2])

In [11]:
vector.ndim

1

In [13]:
#Check shape of vector
vector.shape

torch.Size([2])

In [14]:
#Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR = torch.tensor([[[7,4],[0,1]],[[1, 9],[2, 3]],[[5, 6], [8, 8]]])
TENSOR

tensor([[[7, 4],
         [0, 1]],

        [[1, 9],
         [2, 3]],

        [[5, 6],
         [8, 8]]])

In [21]:
TENSOR.shape

torch.Size([3, 2, 2])

### Random Tensors

In [23]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.4765, 0.6755, 0.5688, 0.2308],
        [0.7998, 0.5347, 0.1290, 0.1851],
        [0.5034, 0.7831, 0.0210, 0.7760]])

In [24]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [26]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [29]:
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [32]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

### Getting information from Tensors
shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in?

device - what device is the tensor stored on? (usually GPU or CPU)

In [35]:
some_tensors = torch.rand(3,4)

print(some_tensors)
print(f"Shape of Tensor:{some_tensors.shape}")
print(f"Data Type of Tensor: {some_tensors.dtype}")
print(f"Device of Tensor: {some_tensors.device}")


tensor([[0.1303, 0.1923, 0.3193, 0.0091],
        [0.8119, 0.6298, 0.3635, 0.9633],
        [0.5973, 0.2264, 0.3410, 0.1690]])
Shape of Tensor:torch.Size([3, 4])
Data Type of Tensor: torch.float32
Device of Tensor: cpu


`Note: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":`
- "what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

### Manipulating tensors (tensor operations)
- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [5]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [6]:
tensor * 10

tensor([10, 20, 30])

In [9]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [7]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [8]:
tensor * tensor

tensor([1, 4, 9])

#### Matrix multiplication (is all you need)

In [10]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [11]:
tensor @ tensor

tensor(14)

### One of the most common errors in deep learning (shape errors)

In [12]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]], dtype=torch.float32)

tensor_A.shape, tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [14]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 89.,  98.],
        [116., 128.]])

In [17]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)

print(f"Input:\n{x}\n")
print(f"Output:\n{output}\nShape of output: {output.shape}")


Input:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
Shape of output: torch.Size([3, 6])


### Finding min, max, mean, sum, etc(aggreration)

In [18]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
print(f"Min: {x.min()}")
print(f"Max: {x.max()}")
# print(f"Mean: {x.mean()}") # error
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Min: 0
Max: 90
Mean: 45.0
Sum: 450


In [24]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max

In [26]:
tensor = torch.arange(0,100,10)
print(tensor)

print(f"Index where is min value: {tensor.argmin()}")
print(f"Index where is max value: {tensor.argmax()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where is min value: 0
Index where is max value: 9


### Change type

In [28]:
tensor = torch.arange(0,100,10)
print(tensor.dtype)
print(tensor.type(torch.float16))

torch.int64
tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)


In [29]:
import torch
x = torch.arange(1.,8.,1.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

### Reshaping, stacking, squeezing and unsqueezing

- torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

- Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

- torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
- torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.
- torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
- torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [31]:
x_reshaped = x.reshape(1,7)
x_reshaped.shape

torch.Size([1, 7])

In [33]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [34]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [37]:
x_stacked = torch.stack([x,x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.]])

In [39]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [40]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


### Indexing

In [42]:
import torch
x = torch.arange(1,10,1).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [43]:
print(x[0])
print(x[0][1])
print(x[0][2][2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor(9)


### PyTorch tensors & NumPy
`The two main methods, you'll use for Numpy to Tensor (back again) are:`
-   torch.from_numpy(array)   : Numpy array --> Pytorch tensor
-   torch.Tensor.numpy()      : Pytorch tensor --> Numpy array

In [47]:
import numpy as np
array = np.arange(1.0,8.0,1)
tensor_from_array = torch.from_numpy(array)
array, tensor_from_array

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [52]:
tensor = torch.ones(7)
array= tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)

In [53]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062]])

Tensor B:
tensor([[0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [57]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])